#!/bin/bash

if [ $1 == "install" -o $1 == "upgrade" ]; then

        if [ -f "/etc/init.d/sickbeard" ]; then
                /etc/init.d/sickbeard stop &>/dev/null;
        fi

        if [ -d "/usr/local/etc/sickbeard/" ]; then

		mv /usr/local/etc/sickbeard /etc/sickbeard

		ln -s /etc/sickbeard /usr/local/etc/sickbeard

	else
		true
	fi

if [ -d "/usr/local/share/sickbeard" ]; then

        versionfile="/usr/local/share/sickbeard/sickbeard/version.py"

        if [ -f "$versionfile" ]; then

                if ! grep -q "ThePirateBay" "$versionfile"; then
                        #backup database because it's not upgrading from a PirateBay branch
                        count=`ls -1 /usr/local/share/sickbeard/*.db* 2>/dev/null | wc -l`
                        if [ $count != 0 ];then
				if [ ! -d "/usr/local/share/sickbeard/old_db_bak" ];then
                                	mkdir /usr/local/share/sickbeard/old_db_bak
				fi
                                mv /usr/local/share/sickbeard/*.db* /usr/local/share/sickbeard/old_db_bak/.
                        fi

                fi

	else

		#try to backup if versionfile is missing
		count=`ls -1 /usr/local/share/sickbeard/*.db* 2>/dev/null | wc -l`
                if [ $count != 0 ];then
			if [ ! -d "/usr/local/share/sickbeard/old_db_bak" ];then
                		mkdir /usr/local/share/sickbeard/old_db_bak
			fi
                	mv /usr/local/share/sickbeard/*.db* /usr/local/share/sickbeard/old_db_bak/.
                fi


        fi



fi


fi
